export const actionTypes = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT: 'LOGOUT',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  CHECK_AUTHORIZATION: 'CHECK_AUTHORIZATION',
  SAVE_TOKEN: 'SAVE_TOKEN',
  EMAIL_SIGNIN: 'EMAIL_SIGNIN',
  PHONE_SIGNIN: 'PHONE_SIGNIN',
};
